### ISSUE TITLE
Council engagement on longer-term policy

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/policy-lab#16]
UPDATE 5/11: Will plan for Council engagement as part of longer-term policy and platform.

Process: Submit a request for Council action to consider a resolution. The resolution will direct CTM to develop rules governing digital signatures. Then we'll begin a process to develop and propose rules. (This issue is just about the RCA)

## To-do:
- [x] Draft an RCA -- examples in the comments below
- [x] Update Tauseef and Stephen on next steps
- [x] Share draft RCA backup doc with Sandra
- [x] Set up a meeting with Sandra to brief Tauseef
- [ ] Draft resolution language -- Sandra will help with this

**Comment by danielhonker** [comment]
Notes from 2013.01.31 meeting with Clerk's Office:
- Name CTM as the lead department
- Keep the resolution language short and sweet. Go find the Georgetown language. Look at other TX cities' artifacts.
- Backup document includes points of contact from all the involved departments.
- Sandra would draft the backup materials. There's a template for this. 
- Need to have someone available to answer questions when the item gets posted. 
- Opportunity to have a content strategist work on this. 

Action items:
- [x] Read the process for CTM RCAs
- [x] Talk to Kristy Pantages -- who handles RCAs for CTM
- [x] Collect artifacts/language from other TX cities
- [ ] Circle back with Tauseef about the next steps
- [ ] After talking with Kristy and Tauseef, circle back with Sandra

**Comment by danielhonker** [comment]
## Resolution and policy language from other TX cities

[Georgetown's passed ordinance on Electronic and Digital Signatures](https://github.com/cityofaustin/policy-lab/files/4141438/COG.ORD.on.Electronic.and.Digital.Signatures.pdf)

[San Antonio's internal policy on digital signatures](https://www.sanantonio.gov/Portals/0/Files/EmployeeInformation/ADs/AD7-4A.pdf)

**Comment by danielhonker** [comment]
[Example agenda backup doc](https://github.com/cityofaustin/policy-lab/files/4162301/InnovationOfficeGrantItem5172019.pdf). Use this to draft content.

**Comment by danielhonker** [comment]
Here's a test comment for the slack integration. Will it work?

**Comment by danielhonker** [comment]
Here's another test of the slack integration... will it work?

**Comment by danielhonker** [comment]
[Drafting the content here](https://docs.google.com/document/d/1loQ3YhBMa8lat1kKVbI5vbxjLQWrHjMDX1WhuUwi6BI/edit#)

**Comment by danielhonker** [comment]
Shared the draft RCA backup document with Sandra and asked to set up a meeting to brief Tauseef.

**Comment by danielhonker** [comment]
Update: Based on Law Dept recommendation, we are approaching city manager for policy, and will pursue a Council item at a later date. Back into the backlog for now...
