### ISSUE TITLE
Create a checklist and intake process for microsites

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/policy-lab#24]
Let's aim to ship a checklist and process recommendation to Tauseef and Peter by March 12, which we think is doable. 

## Tasks
- [x] Draft a checklist for microsite usage and review against existing policy - Honker
- [x] Identify use cases to run through the checklist - Honker & Marni (complete -- did this right after our call)
- [x] Host a workshop to review the checklist and run several use cases through it - Honker. We'll look to schedule this for Mar 9-10 and invite this group as well. 
- [x] Iterate the checklist after workshop
- [x] Draft a workflow for routing microsite proposals through the checklist and connecting them to resources
- [x] Share the checklist and process recommendations with Tauseef and Peter NLT Thursday, March 12. 

## Use cases to test the checklist

1. Auditor's Office request for a redistricting site
2. Homelessness resource site
3. Police Oversight
4. Airport site
5. Vision Zero

## Relevant docs
[Microsite research](https://docs.google.com/presentation/d/1YYubvvJGXMoWgUuO7_6ACQIpnZUH6IY6-jNe3GDJVfg/edit?usp=sharing)

[Desired outcomes of microsite policy](https://docs.google.com/document/d/1mPTqocmoPcGaIL43bJdBocqCt3LGhVcN_uczYyU39hg/edit#)

[Checklist](https://docs.google.com/spreadsheets/d/1IZrIVxWq94yHQ2v7SakQb7uL9FKesAn6wmk_k22XhNA/edit#gid=1222607107)

[Recommendations on policy and process](https://docs.google.com/presentation/d/1UHEQ7x_5jMVEAro948X2HRjeHxJqrrn24KYlDhHxlVQ/edit?usp=sharing)

**Comment by danielhonker** [comment]
![Uploading MVIMG_20200228_102523.jpg…]()

**Comment by danielhonker** [comment]
Whiteboarding from planning session with Marni, James, and Paul today:

![MVIMG_20200228_102523](https://user-images.githubusercontent.com/17604266/75567621-714f6e00-5a17-11ea-8fc9-88c9cd824039.jpg)

**Comment by danielhonker** [comment]
Notes from the workshop today:

Next steps:
1. I will package up the checklist with some recommendations on a process we might use to intake and evaluate requests for microsites. I'll share this by the end of this week.
2. Based on #1, we can discuss potential need for more formal policy documentation and process. 

A few takeaways from our conversation:
- This checklist seems to be helpful for decision making. We'll also need an intake process to collect information about a department's need and tee up a final decision based on all these criteria. We can use a checklist to breakdown different criteria, but the decision is ultimately a strategic decision with lots of room for judgment.
- The two "heaviest" criteria for microsites seemed to be 1) the department's need for separate branding, and 2) their need for features and functionality in comparison to our platform roadmap (Austintexas.gov and Austin.gov). 
- There's ambiguity around branding. It's unclear who should make a decision on whether something needs a distinct brand (CPIO?)

![15837900333926948883663805357627](https://user-images.githubusercontent.com/17604266/76259942-bac46800-6224-11ea-8f2e-38dd64c6858c.jpg)
