### ISSUE TITLE
Synthesize digital services roadmap policy issues and make a plan out of it

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/policy-lab#82]
Following on #48 

Meeting scheduled for 8/19

### To do
- [x] Schedule meeting to synthesize
- [x] Synthesize issues 
- [x] Come up with a way to sequence/prioritize
- [x] Close feedback loop with web team leads
